[2025-07-14 04:52:21 +0000] [26920] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/SES_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn_error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: ses_site.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f33454d6b60>
  on_reload: <function OnReload.on_reload at 0x7f33454d6ca0>
  when_ready: <function WhenReady.when_ready at 0x7f33454d6de0>
  pre_fork: <function Prefork.pre_fork at 0x7f33454d6fc0>
  post_fork: <function Postfork.post_fork at 0x7f33454d7100>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f33454d7240>
  worker_int: <function WorkerInt.worker_int at 0x7f33454d7380>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f33454d74c0>
  pre_exec: <function PreExec.pre_exec at 0x7f33454d7600>
  pre_request: <function PreRequest.pre_request at 0x7f33454d7740>
  post_request: <function PostRequest.post_request at 0x7f33454d77e0>
  child_exit: <function ChildExit.child_exit at 0x7f33454d7920>
  worker_exit: <function WorkerExit.worker_exit at 0x7f33454d7a60>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f33454d7ba0>
  on_exit: <function OnExit.on_exit at 0x7f33454d7ce0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2025-07-14 04:52:21 +0000] [26920] [INFO] Starting gunicorn 20.1.0
[2025-07-14 04:52:21 +0000] [26920] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-07-14 04:52:21 +0000] [26920] [DEBUG] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-07-14 04:52:21 +0000] [26920] [ERROR] Retrying in 1 second.
[2025-07-14 04:52:22 +0000] [26920] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-07-14 04:52:22 +0000] [26920] [DEBUG] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-07-14 04:52:22 +0000] [26920] [ERROR] Retrying in 1 second.
[2025-07-14 04:52:23 +0000] [26920] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-07-14 04:52:23 +0000] [26920] [DEBUG] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-07-14 04:52:23 +0000] [26920] [ERROR] Retrying in 1 second.
[2025-07-14 04:52:24 +0000] [26920] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-07-14 04:52:24 +0000] [26920] [DEBUG] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-07-14 04:52:24 +0000] [26920] [ERROR] Retrying in 1 second.
[2025-07-14 04:52:25 +0000] [26920] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-07-14 04:52:25 +0000] [26920] [DEBUG] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-07-14 04:52:25 +0000] [26920] [ERROR] Retrying in 1 second.
[2025-07-14 04:52:26 +0000] [26920] [ERROR] Can't connect to ('0.0.0.0', 8000)
[2025-07-14 04:57:46 +0000] [27052] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/SES_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn_error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: ses_site.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x793b1e72eb60>
  on_reload: <function OnReload.on_reload at 0x793b1e72eca0>
  when_ready: <function WhenReady.when_ready at 0x793b1e72ede0>
  pre_fork: <function Prefork.pre_fork at 0x793b1e72efc0>
  post_fork: <function Postfork.post_fork at 0x793b1e72f100>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x793b1e72f240>
  worker_int: <function WorkerInt.worker_int at 0x793b1e72f380>
  worker_abort: <function WorkerAbort.worker_abort at 0x793b1e72f4c0>
  pre_exec: <function PreExec.pre_exec at 0x793b1e72f600>
  pre_request: <function PreRequest.pre_request at 0x793b1e72f740>
  post_request: <function PostRequest.post_request at 0x793b1e72f7e0>
  child_exit: <function ChildExit.child_exit at 0x793b1e72f920>
  worker_exit: <function WorkerExit.worker_exit at 0x793b1e72fa60>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x793b1e72fba0>
  on_exit: <function OnExit.on_exit at 0x793b1e72fce0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2025-07-14 04:57:46 +0000] [27052] [INFO] Starting gunicorn 20.1.0
[2025-07-14 04:57:46 +0000] [27052] [DEBUG] Arbiter booted
[2025-07-14 04:57:46 +0000] [27052] [INFO] Listening at: http://0.0.0.0:8000 (27052)
[2025-07-14 04:57:46 +0000] [27052] [INFO] Using worker: sync
[2025-07-14 04:57:46 +0000] [27053] [INFO] Booting worker with pid: 27053
[2025-07-14 04:57:46 +0000] [27053] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/SES_project/ses_site/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
[2025-07-14 04:57:46 +0000] [27053] [INFO] Worker exiting (pid: 27053)
[2025-07-14 04:57:46 +0000] [27052] [INFO] Shutting down: Master
[2025-07-14 04:57:46 +0000] [27052] [INFO] Reason: Worker failed to boot.
